### ISSUE TITLE
能否写一个基于wordpress接口的案例呢？

### ISSUE THREAD

**Issue by skating507** [togayther/react-native-cnblogs#10]
wordpress还是蛮多人使用的，能否把这个改成基于wordpress接口和登录授权的案例呢？

**Comment by togayther** [comment]
@skating507 
你好，该应用是基于博客园官方开放的接口实现的。其登录授权功能，也必须依赖于官方开放的oauth2的登录验证接口。至于wordpress，如果提供了开放的，获取博客数据及登录接口的话，也是可以适配的。

**Comment by skating507** [comment]
WordPress有接口，可以提供WordPress相关接口作为测试

**Comment by togayther** [comment]
@skating507 
以该应用为例。用户必须登录后，才可以查看博文数据及进入个人中心。如果修改为基于 wordpress 接口授权的话，相关的业务也需要调整喔^_^

**Comment by skating507** [comment]
这个调整为去掉必须登录就可以了。
