### ISSUE TITLE
关于redux-thunk和redux-promise的区别

### ISSUE THREAD

**Issue by jingxin2015** [togayther/react-native-cnblogs#11]
1、redux-thunk 不支持标准的action，而且写起来代码也很多，而redux-promise支持标准action，而且写起来代码优雅很多，为什么还要使用redux-thunk？
2、看楼主的代码里还有自己实现promise的代码？没看太懂呢，请帮忙解惑下，谢谢。

**Comment by togayther** [comment]
@jingxin2015 
抱歉，现在才回复你。
1，因为我最开始接触到的就是 redux-thunk 哈，所以这只是一个选择的问题。我会尽快了解一下redux-promise，看是不是有你说的这么多好处^_^。
2，你说的自己实现的 promise 代码，应该是 middleware/promise.js 吧。其实，它只是将诸如 fetch 操作这些结果为 promise 的方法调用，转换为可供reducer 处理的普通对象而已，只是里面混杂了 redux 相关的 dispatch & payload & meta 而已。建议你了解一下 redux 相关的东西哈。可查阅以下地址：
http://www.redux.org.cn/

**Comment by jingxin2015** [comment]
嗯，redux最近一直在看，但是关于中间件的选择上，遇到了问题，呵呵，我的感觉貌似我对promise这个东西理解的还不够，另外关于redux-thunk和redux-promise，我看到了一篇分析的文章，大概就是说redux-promise有个缺点就是不支持乐观更新，这个是那篇文章的地址：https://segmentfault.com/a/1190000007248878
关于作者给出的 redux-action-tool，不知道你怎么看？

**Comment by togayther** [comment]
@jingxin2015 
嗯，看了你贴出来的分析文章，写的很好哈。我个人的话，还是更加倾向于靠近于redux原理的实现，比如 redux-thunk，保留了三个action状态，不仅保留了原文提到的“乐观更新”，同时更容易对action的不同状态做交互上的响应（比如fetch时显示加载状态等），这也是我之前做react应用时习惯采用的方案。至于redux-promise，代码看上去确实精简不少，视不同的业务场景，肯定有其适用范围的。

redux-action-tool的话，有点像我实现的博客园app里面的方式哈（redux-actions）。原文作者给出的示例代码如下：

const GET_DATA = 'GET_DATA';

//action creator
const getData = createAsyncAction(GET_DATA, function(id) {
    return api.getData(id)
})

//reducer
const reducer = createReducer()
    .when(getData, (oldState, action) => oldState)
    .done((oldState, action) => successState)
    .failed((oldState, action) => errorState)
    .build()


而在博客园app中，也仅需要定义一个action type，在action creator 层面，写法也大同小异，以post为例：
export const getPostByCategory = createAction(
  types.FETCH_POSTS_BY_CATEGORY, 
  async(category)=> {
    return await postService.getPostByCategory(category, {
      pageIndex: 1
    });
  }, 
  (category)=> {
    return {
      pending: true,
      category
    }
  }
);

关于 reducer 的处理，与原文对应的，即是我源码中 middleware/promise.js。

希望对你有所帮助。
