### ISSUE TITLE
window下运行安卓出错

### ISSUE THREAD

**Issue by zhouwu5** [togayther/react-native-cnblogs#12]
app:compileDebugJavaWithJavac
C:\Users\zhou\Desktop\React\react-native-cnblogs\android\app\src\main\java\com\reactnativecnblogs\MainApplication.java:40: 错误: 找不到符号
            new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), this, BuildConfig.DEBUG),
                                                          ^
  符号:   变量 reactNativeCodePush_androidDeploymentKey
  位置: 类 string

**Comment by togayther** [comment]
@zhouwu5 
你好，看错误提示信息，应该是codepush集成引起的错误，麻烦git更新一下代码库，并重新安装并集成一下codepush组件试试。
