### ISSUE TITLE
能否解释下middleware目录下每个文件的作用？

### ISSUE THREAD

**Issue by jingxin2015** [togayther/react-native-cnblogs#13]
现在大概单独代码都看明白了，但是还不能形成一个整体流程，middleware中比如 callback.js 、pending.js、promise.js 这三个文件，是否是属于封装的类库类似的，而不是具体的中间件功能？
比如logger.js 很好理解，就是一个记录日志的中间件，麻烦帮忙解惑下，谢谢

**Comment by togayther** [comment]
你好。
对于 callback.js ，是让“前端”支持 resolved/rejected function 的调用。比如添加回复：
    this.props.commentAction.addComment({
          category: this.props.category, 
          params: {
            blogger: this.props.blogger,
            id: this.props.id
          },
          data: commentData,
          resolved: (data)=>{
            this.onCommentResolved(data);
          },
          rejected: (data)=>{
            this.onCommentRejected(data);
          }
        });

对于pending.js，其文件顶部已有所说明：
/*
*  I just use this to fix a bugs about when the request is too quickly, the RefreshControl can't update the refreshing.
*  It's a bug, but I don't know how to fix it, so use this hack way to do it.
* */

对于 promise.js，主要针对 fetch 操作，做了 promise 对象转 reducer 接收对象的一个转换。

上述位于 middleware 的三个文件，其工作机制为 middleware 的中间件。区别于logger.js 这类的中间件。logger.js ，不对后续的数据进行加工处理，仅仅是输出日志文件。而上述三个，或多或少对后续分发（dispatch）的数据进行了处理。
