### ISSUE TITLE
关于Navigator的疑问，谢谢。

### ISSUE THREAD

**Issue by jingxin2015** [togayther/react-native-cnblogs#14]
![qq 20161221235855](https://cloud.githubusercontent.com/assets/16143766/21396082/e1e1d442-c7d9-11e6-904b-0cbb2bf37a11.png)

上图中，红框中的 this.router 是指什么？
另外楼主，请教下，闲鱼那样的tabbar不知道好实现不，或者有相关的库可以推荐的？
楼主用的那个react-native-action-button，多个按钮可以横向排列吗？

闲鱼app底部tabbar的截图传不上来了，就是中间有一个圆形的发布图标的那种，顺便贴个点击发布后的效果图，这个效果是不是用 react-native-action-button 就可以实现呀？
![default](https://cloud.githubusercontent.com/assets/16143766/21396469/5a525ea0-c7db-11e6-8a41-997378400b7a.png)

**Comment by togayther** [comment]
@jingxin2015 
你好，this.router ，其实就是一个对象变量。this.router = this.router || new Router(navigator); 仅初始化该变量一次。
类似闲鱼这样的 action button，和现有博客园引入的 react-native-action-button，行为很相近。但我不确定有无现成的第三方组件可供使用。不过可以 fork => react-native-action-button ，进行自定义修改哈。

**Comment by jingxin2015** [comment]
嗯，明白了，我再研究研究，谢谢。

**Comment by togayther** [comment]
ok
