### ISSUE TITLE
Possible Unhandled Promise Rejection (id:5):undefined is not an object(evaluating 'RCTToast.show')

### ISSUE THREAD

**Issue by hqwlkj** [togayther/react-native-cnblogs#15]
作者你好：
        运行的时候出现了以下如图的问题：
<img width="375" alt="qq20161222-165947 2x" src="https://cloud.githubusercontent.com/assets/12181423/21420597/94f823b2-c869-11e6-9cb8-ec426c8dcf80.png">
好像是这个插件“@remobile/react-native-toast”的问题，
请教以下应该如何处理。

**Comment by hqwlkj** [comment]
哈哈  自己居然解决了这个问题了：

下面是我的解决方法：

1. In the XCode's "Project navigator", right click on Libraries folder under your project -> Add Files to <...>
2. Go to node_modules ->  @remobile -> react-native-toast -> ios  and add the RCTToast.xcodeproj file
3. Add libRCTToast.a to Build Phases -> Link Binary With Libraries

**Comment by togayther** [comment]
@hqwlkj 
嗯，对的。你这是手动添加依赖包的方式哈。还可以直接 react-native link
