### ISSUE TITLE
能不能帮忙解释下 redux-actions 的createAction 函数参数？

### ISSUE THREAD

**Issue by jingxin2015** [togayther/react-native-cnblogs#16]
redux-actions 的createAction 函数的后面两个参数一直没理解透
下图中两个action，为什么refreshToken需要定义 resolved和rejected，而getUserAssetByCategory却没有？
是get都没有吗？

pending 是什么意思？ 显示转圈的雪花吗？ 谢谢。

![1622](https://cloud.githubusercontent.com/assets/16143766/21472441/011e3bf0-cb15-11e6-9f35-422dd60e1901.jpg)

**Comment by togayther** [comment]
@jingxin2015 
你好，红框标注的地方，其接收参数的语法，是es6的对象的解构赋值。而 createAction 方法的定义，接收三个参数：createAction(type, payloadCreator = Identity, ?metaCreator)，这里的 metaCreator，顾名思义，即 meta 构造（构造一个对象）。构造出的meta对象，可在随后的 middleware/reducer 中进行读取使用。

第一个红框标注处，meta对象包含的：resolved & rejected，是方便调用后，进行成功&错误处理的。其原理请查看 middleware/callback.js ，一看便知。

第二个红框标注处，meta对象包括的：pending，是标注前端呈现加载状态的。其原理请查看 middleware/pending.js。

这里可以根据业务 & 交互的需要，灵活的决定是否需要在相应的方法调用中，指定 resolved & rejected & pending 等。

**Comment by jingxin2015** [comment]
第一个红框处，是不是不需要用解构赋值？直接写成这样 (token,resolved,rejected)=>{
　return{
　　token,
　　resolved,
　　rejected
　}
}
因为给　token,resolved,rejected　三个变量解构赋值后，后面也没有使用到呀，包括上面 async({token})=>{}，是不是也不需要解构赋值，不知道我理解的对不？

**Comment by togayther** [comment]
可以写成：
 (token,resolved,rejected)=>{
　return{
　　token,
　　resolved,
　　rejected
　}
}

但你在 view 调用 refreshToken 的时候，传入参数的方式，需要做出调整。

**Comment by jingxin2015** [comment]
嗯。这个issue可以close啦。谢谢
