### ISSUE TITLE
reducer里每个都分成两个一个带ui的，设计思路是怎样的呢？

### ISSUE THREAD

**Issue by jingxin2015** [togayther/react-native-cnblogs#18]
如题，发现reducers文件夹里，比如 author.js authorUI.js，基本上每个都分成了两个文件，不知道这样的设计是为什么呢，有什么好处？谢谢

**Comment by togayther** [comment]
@jingxin2015 
你好，将数据本身，和其状态信息，拆分开，方便管理及前端view进行判断处理。具体，你可以参考一下view页面的逻辑。

**Comment by jingxin2015** [comment]
嗯，好的，谢谢
