### ISSUE TITLE
部分博文获取不到数据

### ISSUE THREAD

**Issue by zhaohuiyingxue** [togayther/react-native-cnblogs#2]
例如：http://www.cnblogs.com/yuangang/p/5600860.html

**Comment by togayther** [comment]
嗯，这个问题我已经在 http://www.cnblogs.com/mcmurphy/p/5581689.html 进行了说明。实际测试过程中，发现博客园部分接口非常不稳定，比如博主详情接口，还有就是你上面提到的博文详情接口，经常无数据返回，这也是我比较困惑的点。我打算发邮件给dudu求证一下。

**Comment by togayther** [comment]
新版已解决。
