### ISSUE TITLE
密码输入框竟然是明文显示。。。

### ISSUE THREAD

**Issue by xuanskyer** [togayther/react-native-cnblogs#20]
密码输入框竟然是明文显示。。。

**Comment by togayther** [comment]
@xuanskyer

嘿嘿，这是特性。

**Comment by hqwlkj** [comment]
@xuanskyer  可以参考此文章
http://facebook.github.io/react-native/docs/textinput.html

secureTextEntry?: bool 

If true, the text input obscures the text entered so that sensitive text like passwords stay secure. The default value is false.
