### ISSUE TITLE
账号问题

### ISSUE THREAD

**Issue by wu464995183** [togayther/react-native-cnblogs#21]
亲 ..  为什么向contact@cnblogs.com索要clientId、clientSecret、rsa加密公钥没人回复啊?

**Comment by togayther** [comment]
@wu464995183
不好意思，现在才回复你。

对个人开发者开放，申请博客园api访问权限相关的配置参数，需要您提供以下信息：
真实姓名、手机号码、常用邮箱、App介绍。

一般一至两个工作日，博客园团队会进行回复的。

你可以再耐心等待一下。或者直接在博客园官方网站，@dudu 咨询一下。

**Comment by wu464995183** [comment]
恩 ..刚刚收到了,非常感谢,博主....

**Comment by togayther** [comment]
@wu464995183 

客气。

**Comment by sysoft** [comment]
github找其它cnblog项目，有些人把key直接提交了，只能帮你到这了😂
