### ISSUE TITLE
授权信息 的配置方式是否不安全？

### ISSUE THREAD

**Issue by Qiulvwen** [togayther/react-native-cnblogs#24]
是否很容易被解包后拿到那段代码。

**Comment by togayther** [comment]
@Qiulvwen 
你好，软件在发布到应用市场的时候，会通过正规的加固软件进行加固，一定程度上防范了被人解包的风险。

**Comment by Qiulvwen** [comment]
@togayther 谢谢，一般是用那些加固软件呢？它们是给 App 加壳，还是防止反编译？

**Comment by togayther** [comment]
@Qiulvwen 
可以参考以下链接：
http://jiagu.360.cn/
