### ISSUE TITLE
站内链接建议不使用浏览器打开而在软件中直接打开

### ISSUE THREAD

**Issue by zhaohuiyingxue** [togayther/react-native-cnblogs#3]

**Comment by togayther** [comment]
嗯，很好的一个建议。技术实现上，只需要解析博客数据，若判断链接为博客园内部跳转，则不进行外部浏览器打开。感谢你的反馈，后续我会抽空实现这个功能。

**Comment by togayther** [comment]
@zhaohuiyingxue 
外部链接，已统一调整为通过react-native内置的webview打开。感谢关注！
