### ISSUE TITLE
reduce相关文件中，return的时候，类似[category]:results，[]是什么语法呢？

### ISSUE THREAD

**Issue by gufanyuanying** [togayther/react-native-cnblogs#33]
``
	return {  
		...state,  
		[category]: results  
	};  
``
return时，category为什么要加[]呢？

**Comment by togayther** [comment]
@gufanyuanying 
抱歉现在才回复你。本质就是对象动态赋值哈。类似： obj[变量] = xxx;

**Comment by gufanyuanying** [comment]
@togayther 谢谢你的回答，不过还有一些疑问，麻烦你讲讲。
![wx20170713-114032](https://user-images.githubusercontent.com/10770502/28149485-7f3589a6-67c0-11e7-9cf7-ef4be862ceae.png)

ps：这个语法术语叫什么呢，网上搜什么关键字可以看到相关讲解呢

**Comment by togayther** [comment]
@gufanyuanying 
你好，可简单看一下这个：
https://segmentfault.com/q/1010000007022743

**Comment by gufanyuanying** [comment]
@togayther 谢谢，懂了。
