### ISSUE TITLE
搞个服务器弄点模拟数据即可, 不必调用cnblogs的数据啊

### ISSUE THREAD

**Issue by HappyToper** [togayther/react-native-cnblogs#35]
搞个服务器弄点模拟数据即可, 不必调用cnblogs的数据啊

**Comment by togayther** [comment]
@shangduanzi 
抱歉现在才回复你。最开始一直是调用的博客园官方的接口数据哈，但最近博客园在对其openapi进行重构，以防范大范围的暴力攻击风险，所以接口现在就不能用了。

由于时间关系，暂时不考虑做模拟数据哈。相关项目源代码，仅供参考。
