### ISSUE TITLE
登陆失败及崩溃的问题

### ISSUE THREAD

**Issue by cooaer** [togayther/react-native-cnblogs#6]
1，各种重试，仍然登陆失败，用户名密码没有问题
<br />2，在登陆对话框点击“放弃”和在登陆界面点击”没有账号，点此注册“都会崩溃，错误原因是”NetworkOnMainThreadException“

备注：我运行的是自己手动编译的版本。崩溃的问题，应该是启动了严格模式，在移动网络下没有问题，只有在Wifi网络下会崩溃。下载安装正式版没有出现问题。
设备：Nexus 6P
系统：Android 7.0

**Comment by togayther** [comment]
早上好，非常感谢你的反馈！
请问你是下载的源代码配置本地运行，还是下载的apk安装包运行呢？ 另外，可否提供一下你安卓系统的版本呢？

**Comment by cooaer** [comment]
@togayther 已重新编辑问题

**Comment by togayther** [comment]
@cooaer 手动编译的话，需要在文件：source/config/index.js，配置博客园接口授权信息，包括clientId, clientSecret 和 rsa加密公钥。崩溃的问题，我会核实一下。

**Comment by cooaer** [comment]
@togayther 明白了，多谢！

**Comment by togayther** [comment]
@cooaer okay.
