### ISSUE TITLE
真机部署调试报这个异常

### ISSUE THREAD

**Issue by zhaoweijing2003** [togayther/react-native-cnblogs#7]
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'reactNativeCnblogs'.
  > Could not resolve all dependencies for configuration ':classpath'.
  > Could not resolve com.android.tools.build:gradle:1.3.1.
   Required by:
       :reactNativeCnblogs:unspecified
    > Could not resolve com.android.tools.build:gradle:1.3.1.
       > Could not get resource 'https://jcenter.bintray.com/com/android/tools
  /build/gradle/1.3.1/gradle-1.3.1.pom'.
          > Could not GET 'https://jcenter.bintray.com/com/android/tools/build
  /gradle/1.3.1/gradle-1.3.1.pom'.
             > 这是在主机名解析时通常出现的暂时错误，它意味着本地服务器没有从
  权威服务器上收到响应。

**Comment by togayther** [comment]
@zhaoweijing2003 

你好，本地手动编译调试的话，需要在文件：source/config/index.js，配置博客园接口授权信息，包括clientId, clientSecret 和 rsa 加密公钥。
