### ISSUE TITLE
您好，问下authData 怎样申请

### ISSUE THREAD

**Issue by Mrjingfu** [togayther/react-native-cnblogs#8]
export const authData = {
	pubKey : "", //向博客园申请后填入
 	clientId: "",//向博客园申请后填入
 	clientSecret: ""//向博客园申请后填入
};

**Comment by togayther** [comment]
你好，对于个人开发者，需要提供以下信息：
真实姓名、手机号码、常用邮箱、相关app介绍。
邮件发送至： contact@cnblogs.com

**Comment by GitHubDevLop** [comment]
我编译成功。运行后报server handler error，怎么破啊

**Comment by togayther** [comment]
@GitHubDevLop  你好，需要修改 source/config/index.js 相关的 authData 配置信息，该信息需要向博客园官方申请。参考以上描述。实在抱歉上述信息不能公开。

**Comment by jony-w** [comment]
在吗？ 我想请问一下，如何申请博远的ClientId, ClientSecret，rsa加密公钥等 这些东西啊？ 我没有看到有注册，申请的地方啊？ 还是说直接给contact@cnblogs.com 他们发邮件就可以了呢？ 他们就会回复呢？

**Comment by togayther** [comment]
@jonyshi 
你好，直接邮件申请即可。对于个人开发者，需要提供以下信息：
真实姓名、手机号码、常用邮箱、相关app介绍。
邮件发送至： contact@cnblogs.com

博客园团队会很快回复的。

**Comment by jony-w** [comment]
@togayther 您好！
  请问下，如果没有ClientId, ClientSecret，rsa加密公钥等这些东西，启动会报错吗？我这里启动报错，现在还没拿到公钥哪些东西。 错误信息如下
- What went wrong:  
  A problem occurred configuring project ':app'.
  
  > Cannot evaluate module react-native-code-push : Configuration with name 'default' not found.
- Try:  
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by togayther** [comment]
@jonyshi 

你好，如果不配置clientid, clientsecret, rsa加密公钥，本地运行调试是不会报错的，仅仅是无法登录。

从你贴出的错误信息来看，应该是无法解析react-native-code-push依赖包的问题。可以试试删除该依赖包，然后重新 npm install react-native-code-push --save，再 react-native link react-native-code-push 试试。具体配置，可参考 https://github.com/Microsoft/react-native-code-push 官方说明。

**Comment by jony-w** [comment]
@togayther 
您好！
    我已经按照您说的处理了，现在项目可以启动，我还是有几个问题想请问一下您？
          1，一般情况下我们的RN项目，在cmd中run启动，他会自动打开app，您这个没有自动打开？
          2，如果我现在没有博园的账号密码，那我打开显示登陆页面，我选择放弃登陆，他就自动关闭了，这是正常情况吗？
          3，博园我已经给他们发邮件了，填写了真实姓名、手机号码、常用邮箱、相关app介绍。
邮件发送至： contact@cnblogs.com，一直没有回复，您是园博博主吗？

**Comment by togayther** [comment]
@jonyshi

你好，对于你提到的三个问题：
1，这个项目，没有针对app的启动做特别的控制哈，可直接参考rn官方的调试启动方式。以安卓真机调试为例，通常为以下步骤：
（1）连接设备
（2）cmd 至 项目目录，adb kill-server
（3）react-native run-android
2，在登录弹窗，有两个按钮，一个大大的登录，一个小小的放弃。点击登录，则进入登录页面。放弃的话，则是直接退出应用（主要针对没有博客园账号，而又不想注册的非目标用户）。就是这样设计的哈。
3，我之前申请相关授权信息，博客园团队都是很快就回复了的，当然也因情况而异。你可以再等等哈。我有在博客园写过博客，地址为：http://www.cnblogs.com/mcmurphy

感谢关注！

**Comment by dalehqb** [comment]
contact@cnblogs.com,发给他们了，但是没有回复，怎么办呢？
