### ISSUE TITLE
你好，可不可以写一篇关于这个app的整理实现思路的介绍？

### ISSUE THREAD

**Issue by jingxin2015** [togayther/react-native-cnblogs#9]
刚刚开始学习RN，感觉自己新建一个项目后无从下手，整个app涉及到的东西貌似还是很多的，看这个app的项目结构跟我看的F8的app差不多，可否写篇博文介绍下呢？而且整个app从启动到某一条流程完成，整个执行过程还不是很清晰，对于新手来说可能理解起来有些难度，这方面介绍的文章也很少，期待。

**Comment by togayther** [comment]
@jingxin2015 不好意思，现在才回复你。关于你提到的整理一篇博文介绍该APP的运行流程，等这段时间忙完了，会优先考虑哈。下面我将比较核心的点简单提一下：

1，app启动时，会首先进入 startup 页面，该页面读取授权信息。读取到，则进入首页(home)。如未登录过，则要求用博客园账号登录(跳转至login页面)。（登录过程基于oauth）。
2，整个源码的核心，其数据状态控制及数据流转的流程，基于 redux。相关概念包括：action, middleware, store等，该项目的文件夹结构，已经很直白的体现出来了哈。可参考文档：http://camsong.github.io/redux-in-chinese/index.html 进行redux相关的学习。
3，弄清楚了redux，基本上就没有什么问题了哈。主要就是react/react-native/fetch/promise/es6等相关的技术点。这些都属于react-native开发的必备知识储备。

希望对你的学习之路有所帮助！

**Comment by jingxin2015** [comment]
你好，感谢您的解答，正在学习redux，期待您的文章。
顺便再问个问题，哪个是startup页面呢？

**Comment by togayther** [comment]
@jingxin2015 
你好，应用启动时默认加载的 startup 页面，即 source/view/startup.js。
附：默认页面的配置，位于 source/component/navigation.js。
